name: CloudFormation

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
   

jobs:
  cluster:
    name: Deploy stack to AWS
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.TEAM3_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.TEAM3_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1

    - name: deploy lambda
      run: aws cloudformation deploy --template-file deployment.yaml --stack-name team4-cf-lambda --s3-bucket team-4-zip-temp-bucket --region eu-west-1 --parameter-overrides S3CSVBucketName=awaynetesttrigger DeploymentBucket=team-4-zip-temp-bucket DeploymentPackageKey=lambda.zip --capabilities CAPABILITY_IAM


